name: 'Unit test'

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main-1'

jobs:
  run_unit_tests:
    name: "run unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Run unit tests
        run: go test

